# Point counts from PARI for the Rust canonical-lift counter (src/curvegen/agm/).
#
#   nix develop .#math -c sage sage/agm_vectors.sage > tests/common/agm_vectors.rs
#   nix fmt
#
# E_B : y^2 + xy = x^3 + x^2 + B, with B as an integer whose bit i is the
# coefficient of z^i. GF(2^109) and GF(2^13) check that the counter follows
# its modulus (a pentanomial each) and, at m = 13 < 66, the q/N term of t.
import hashlib, sys

R.<t> = GF(2)[]


def k_from_int(K, c):
    return K(ZZ(c).digits(2))


def b_values(m, n, tag):
    """1 (the Koblitz curve, j in GF(2)) and n - 1 hashed nonzero B."""
    out = [1]
    i = 0
    while len(out) < n:
        d = hashlib.sha256(("ephemeral-ecmh/agm-vectors/%s/%d" % (tag, i)).encode()).digest()
        v = int.from_bytes(d[:16], "little") & (2^m - 1)
        if v > 1:
            out.append(v)
        i += 1
    return out


FIELDS = [
    ("GF127", t^127 + t^63 + 1, 50),
    ("GF109", t^109 + t^5 + t^4 + t^2 + 1, 8),
    ("GF13", t^13 + t^4 + t^3 + t + 1, 8),
]

out = sys.stdout
out.write("// @generated by sage/agm_vectors.sage; do not edit. Regenerate from the repository root:\n")
out.write("//   nix develop .#math -c sage sage/agm_vectors.sage > tests/common/agm_vectors.rs && nix fmt\n")
out.write("#![allow(dead_code)]\n\n")
for name, f, n in FIELDS:
    m = f.degree()
    K = GF(2^m, "z", modulus=f)
    out.write("/// (B, #E_B) over GF(2)\\[z\\]/(%s).\n" % str(f).replace("t", "z"))
    out.write("pub const %s: &[(u128, u128)] = &[\n" % name)
    for b in b_values(m, n, name):
        E = EllipticCurve(K, [1, 1, 0, 0, k_from_int(K, b)])
        out.write("    (0x%x, 0x%x),\n" % (b, E.order()))
    out.write("];\n\n")
    print("%s: %d curves" % (name, n), file=sys.stderr)
