# GF(2^109) for the 14-byte binary variant (src/field/gf2_109/mod.rs, src/curve/binary109/):
# modulus choice, the group structure over it, and the field's constant tables.
#
#   nix develop .#math -c sage sage/gf2_109.sage > src/field/gf2_109/tables.rs
#   nix fmt
#
# The report goes to stderr; stdout is the Rust tables.
import sys

say = lambda *a: print(*a, file=sys.stderr)
R.<t> = GF(2)[]
m = 109

# --- modulus ---------------------------------------------------------------
# Swan: m = 109 = 5 mod 8, so every trinomial t^109 + t^k + 1 has an even
# number of factors.
assert not any((t^m + t^k + 1).is_irreducible() for k in range(1, m))
say("irreducible trinomials of degree 109: none")

# Elements live in 128 bits and are reduced modulo t^19 f, so that t^128 folds
# onto rho = t^19 (f - t^109) with carry-less multiplications (src/field/gf2_109/mod.rs).
# Two folds suffice while deg rho = 19 + k3 < 64 and 2 deg rho < 128, i.e.
# k3 <= 44: every such f costs the same, so take the lowest.
pentas = [(k3, k2, k1) for k3 in range(3, 45) for k2 in range(2, k3) for k1 in range(1, k2)
          if (t^m + t^k3 + t^k2 + t^k1 + 1).is_irreducible()]
k3, k2, k1 = pentas[0]
f = t^m + t^k3 + t^k2 + t^k1 + 1
say("lowest pentanomial: %s (of %d with k3 <= 44)" % (f, len(pentas)))
assert (k3, k2, k1) == (5, 4, 2)
K.<z> = GF(2^m, modulus=f)


def k_to_int(v):
    return ZZ(v.polynomial().change_ring(ZZ)(2))


def half_trace(v):
    return sum(v^(2^(2 * i)) for i in range(55))


rho = 2^19 * (2^k3 + 2^k2 + 2^k1 + 1)
tr_bits = [i for i in range(128) if (z^i).trace() == 1]
say("Tr(z^i) = 1 for i in 0..128 exactly at", tr_bits)
assert tr_bits == [0, 105, 107, 109]
assert half_trace(K(1)) == 1  # 55 terms
sqrt_z = z.sqrt()
say("sqrt(z) has %d terms" % len(sqrt_z.polynomial().exponents()))

# --- the group: E : y^2 + xy = x^3 + x^2 + B, #E = 2r ----------------------
# For a = 1, P is a double iff Tr(x(P)) = Tr(a) = Tr(1) = m mod 2 = 1, so
# E[r] = 2E = {Tr(x) = 1} + O as for m = 127; the one point of order 2,
# (0, sqrt B), has Tr(0) = 0 and x = 0 is free to encode O.
q = ZZ(2)^m
HASSE = isqrt(4 * q)
R_MIN = (q + 1 - HASSE) // 2
say("q = 2^109: HASSE = floor(2 sqrt q) = %d, R_MIN = %d" % (HASSE, R_MIN))
set_random_seed(109)
ncurves, npoints, ordered = 0, 0, []
while ncurves < 8:
    B = K.random_element()
    E = EllipticCurve(K, [1, 1, 0, 0, B])
    n = E.order()
    if n % 4 != 2 or not (n // 2).is_pseudoprime():
        continue
    r = n // 2
    ncurves += 1
    ordered.append(r)
    assert E(0, B.sqrt()).order() == 2
    for _ in range(64):
        P = E.random_point()
        if P.is_zero():
            continue
        npoints += 1
        assert (P[0].trace() == 1) == (r * P).is_zero()
say("Tr(x) = 1 <=> r P = O: %d random points on %d random curves of order 2r" % (npoints, ncurves))
rho_cost = [float(log(sqrt(pi * r / 4), 2)) for r in ordered]
say("generic rho with negation, sqrt(pi r / 4): 2^%.2f .. 2^%.2f" % (min(rho_cost), max(rho_cost)))

# GHS: 109 is prime and d = ord_109(2) = 36, so for B not in GF(2) the magic
# number is at least 36 (sage/ghs.sage): genus >= 2^35.
d = Mod(2, m).multiplicative_order()
say("ord_109(2) = %d: GHS genus >= 2^%d for every B not in GF(2)" % (d, d - 1))
assert d == 36

# --- Rust tables -------------------------------------------------------------
out = sys.stdout
out.write("// @generated by sage/gf2_109.sage; do not edit. Regenerate from the repository root:\n")
out.write("//   nix develop .#math -c sage sage/gf2_109.sage > src/field/gf2_109/tables.rs && nix fmt\n\n")
out.write("/// rho = z^19 (z^%d + z^%d + z^%d + 1) = z^128 mod z^19 f\n" % (k3, k2, k1))
out.write("pub const RHO: u64 = 0x%x;\n\n" % rho)
out.write("/// sqrt(z) = z^(2^108)\n")
out.write("pub const SQRT_Z: u128 = 0x%x;\n\n" % k_to_int(sqrt_z))
out.write("/// H(z^(2i+1)) for i in 0..54: the half-trace of each odd monomial\n")
out.write("pub const HALFTRACE: [u128; 54] = [\n")
for i in range(54):
    out.write("    0x%028x,\n" % k_to_int(half_trace(z^(2 * i + 1))))
out.write("];\n")
