# GF(2^127) = GF(2)[z]/(z^127 + z^63 + 1) (src/field/gf2_127/): the half-trace
# of each basis element, for the table half-trace.
#
#   nix develop .#math -c sage sage/gf2_127.sage > src/field/gf2_127/tables.rs
#   nix fmt
#
# The report goes to stderr; stdout is the Rust file.
import sys

say = lambda *a: print(*a, file=sys.stderr)
R.<x> = GF(2)[]
f = x^127 + x^63 + 1
assert f.is_irreducible()
F.<z> = GF(2^127, modulus=f)


def half_trace(a):
    # H(a) = sum of a^(4^i), i = 0..=63: H^2 + H = a + Tr(a)
    return sum(a^(4^i) for i in range(64))


def to_int(a):
    return ZZ(a.polynomial().change_ring(ZZ)(2))


hs = [half_trace(z^i) for i in range(127)]
for i, h in enumerate(hs):
    assert h^2 + h == z^i + (z^i).trace()
# Tr(v) = v_0 on canonical elements, which the tables and the tests rely on
assert all((z^i).trace() == (1 if i == 0 else 0) for i in range(127))
say("gf2_127: %d half-traces, H^2 + H = v + Tr(v) for each" % len(hs))

out = sys.stdout
out.write("// @generated by sage/gf2_127.sage; do not edit. Regenerate from the repository root:\n")
out.write("//   nix develop .#math -c sage sage/gf2_127.sage > src/field/gf2_127/tables.rs && nix fmt\n\n")
out.write("/// H(z^i) for i in 0..127: the half-trace of each canonical bit\n")
out.write("pub const HALFTRACE: [u128; 127] = [\n")
for h in hs:
    out.write("    0x%032x,\n" % to_int(h))
out.write("];\n")
