# GHS / Weil descent check for y^2 + xy = x^3 + u x^2 + B over GF(2^122)
# (src/curvegen/select122.rs), dense B and GLS B = beta^4 with beta in GF(2^61).
#
#   nix develop .#math -c sage sage/ghs122.sage
#
# GF(2^122)'s proper subfields of size > 2 are GF(2^61) and GF(4) (and GF(2)
# below both): descents of degree n = 2, 61 and 122. For the descent to
# k = GF(2^l), sigma = x -> x^(2^l), GHS's magic number is
#   m = dim_F2 Span{(1, sigma^i(sqrt B)) : 0 <= i < n},
# and the curve C has genus 2^(m-1) or 2^(m-1) - 1 when n is odd, m = n,
# or Tr(a) = 0 (GHS 2002, Thm. 1). Otherwise (n even, Tr(u) = 1, m < n:
# some of the n = 2 and 122 cases here) the descent needs Hess's
# generalization; the check allows it one more dimension, which changes none
# of the conclusions below: m >= 60 still means genus >= 2^58.
#
# The span is the F2[sigma]-module generated by sqrt(B), plus one. Over
# GF(2), x^122 - 1 = (x + 1)^2 Phi_61(x)^2 and Phi_61 is irreducible, as
# ord_61(2) = 60; GF(2^122) is a free F2[x]/(x^122 - 1)-module of rank 1
# (normal basis) with sigma = x^l, so the cyclic submodules have the
# dimensions that the divisors of the annihilator allow:
#   n = 122 (sigma = x):   1, 2, 60, 61, 62, 120, 121, 122
#   n = 61  (sigma = x^2): 1, 60, 61
#   n = 2   (sigma = x^61): 1, 2
# and the small ones (<= 2) are exactly sqrt(B) in GF(4) for n = 122 and 61.
#
# A descent only helps if Jac(C)(k), of about 2^(l g) points, can hold E[r]
# (r ~ 2^121) and index calculus on it beats rho. m <= 2 over GF(2) or
# GF(4) gives g <= 2 (4 with the a term): at most about 2^16 points, so
# E[r] maps to 0. m >= 60 gives g >= 2^58. Neither is weak, so no B is
# GHS-weak for n = 122 or 61. What B in GF(4) is instead: a subfield
# (Koblitz) curve, defined over GF(4) with a = u, whose Frobenius gains
# rho a factor sqrt(61); select122 skips those B (and GLS beta in GF(2)).
# n = 2 gives g <= 2 (4) over GF(2^61) for every curve, where index
# calculus costs about q = 2^61 for g = 2 (more above), against rho's 2^60.3
# (dense) or 2^59.8 (GLS).
import sys
from collections import Counter

R.<x> = GF(2)[]
assert Mod(2, 61).multiplicative_order() == 60
assert sorted((p.degree(), e) for p, e in (x^122 - 1).factor()) == [(1, 2), (60, 2)]
print("x^122 - 1 = (x + 1)^2 Phi_61^2 over GF(2), Phi_61 irreducible (ord_61(2) = 60)")

K.<g> = GF(2^122)
U = sorted((x^2 + x + 1).change_ring(K).roots(multiplicities=False))[0]
W = sorted((x^61 + x^23 + x^15 + x^5 + 1).change_ring(K).roots(multiplicities=False))[0]
V = K.vector_space(map=True)[2]


def magic(B, l):
    s, rows = B.sqrt(), []
    for _ in range(122 // l):
        rows.append([1] + list(V(s)))
        s = s^(2^l)
    return matrix(GF(2), rows).rank()


def sub61():
    """A random element of GF(2^61) inside K."""
    return sum(ZZ.random_element(2) * W^i for i in range(61))


# B in GF(4) \ {0}: m <= 2 everywhere, and a subfield curve
print("\nB in GF(4), the curves defined over GF(4):")
for name, B in [("1", K(1)), ("u", U), ("u^2", U^2)]:
    E = EllipticCurve(K, [1, U, 0, 0, B])
    n = E.order()
    ms = (magic(B, 1), magic(B, 2), magic(B, 61))
    assert max(ms) <= 2
    print("  B = %s: m = %d, %d, %d (n = 122, 61, 2); #E = 2 * %s%s" % (
        (name,) + ms + (factor(n // 2), " (prime)" if (n // 2).is_prime() else "")))
print("  (a prime r here would still be a Koblitz curve over GF(4): skipped)")

set_random_seed(122)
N = 500
dense = Counter(tuple(magic(B, l) for l in (1, 2, 61)) for B in (K.random_element() for _ in range(N)))
gls = Counter(tuple(magic(b^4, l) for l in (1, 2, 61)) for b in (sub61() for _ in range(N)) if b not in (0, 1))
print("\nmagic numbers (n = 122, 61, 2), %d samples each:" % N)
print("  dense B:", dict(sorted(dense.items())))
print("  GLS B = beta^4, beta in GF(2^61) \\ GF(2):", dict(sorted(gls.items())))
assert all(m1 >= 60 and m2 >= 60 and m3 <= 2 for m1, m2, m3 in dense)
assert all(m1 >= 60 and m2 >= 60 and m3 == 1 for m1, m2, m3 in gls)
print("""
So: to GF(2) and GF(4), genus >= 2^58 for every candidate select122 takes;
to GF(2^61), genus <= 2 (4 at most with the a term), where index calculus
costs about q = 2^61 and rho already costs 2^60.3 (dense) or 2^59.8 (GLS).
No per-curve check is needed beyond skipping the subfield curves.""")
