# What the Sage KAT generators share: the byte framing of src/hash.rs, the
# certificate search helpers, the seeds and the `CertKat` emitter. Loaded by
# sage/kat.sage, which is run from
# the repository root:
#
#   nix develop .#math -c sage sage/kat<family>.sage > tests/common/kats<family>.rs
#
# Each generator keeps what is its own: the field and its integer form, the
# curve model, the point codec, the candidate filter and the label rule.
# Rejection witnesses are the Rust prover's (src/curvegen/prove.rs): points
# hashed under TAG_WITNESS with message j || i, taken to the label's order
# by `point_of_order`. Nothing here draws random numbers, so a run
# reproduces every byte.
import hashlib, sys


# --- framing (src/hash.rs) ---------------------------------------------------
def salted(tag, salt, msg, ctr):
    t = hashlib.sha256(tag).digest()
    return hashlib.sha256(t + t + salt + bytes(32) + msg + int(ctr).to_bytes(4, "little")).digest()


def halves(d):
    return [int.from_bytes(d[:16], "little"), int.from_bytes(d[16:], "little")]


def digest_half(tag, seed, j):
    """The first half of the tagged digest of j: the raw material of candidate j."""
    return halves(salted(tag, seed, b"", j))[0]


# --- the search ----------------------------------------------------------------
def small_factor(n, full=True):
    """Smallest prime factor of odd composite n: by trial division below 2^16,
    then by factoring it, or None when `full` is off."""
    for l in primes(3, 2^16):
        if n % l == 0:
            return l
    return factor(n)[0][0] if full else None


EMBEDDING_MIN = 2^20


def mov_ok(q, r):
    """The embedding degree of r over F_q exceeds EMBEDDING_MIN (Rust's constant)."""
    return Mod(q, r).multiplicative_order() > EMBEDDING_MIN


TAG_WITNESS = b"ephemeral-ecmh/prove/witness"


def witness_msg(j, i):
    """The prover's message for the i-th hashed try on candidate j: j || i, u32 LE."""
    return int(j).to_bytes(4, "little") + int(i).to_bytes(4, "little")


def point_of_order(m, l, hash_):
    """A point of order exactly l (a prime, or 8) from hashed points of a
    group of order m, as the prover's `prime_power_point`: the i-th hashed
    point times m with its l-part removed has order a power of the prime
    under l; multiplying by that prime until l kills it leaves order l,
    unless the point was O or fell short of l, when the next i is tried.
    (m/l)*R alone is not enough: if E[l] = Z/l x Z/l, it is always O."""
    base = 2 if l == 8 else l
    k = m
    while k % base == 0:
        k //= base
    i = 0
    while True:
        P = k * hash_(i)
        i += 1
        if P.is_zero():
            continue
        while not (l * P).is_zero():
            P = base * P
        if not ((l // base) * P).is_zero():
            return P


def gf2_from_int(K, c):
    """The element of K = GF(2^n) in polynomial basis whose coefficients are the bits of c."""
    return K(ZZ(c).digits(2))


def gf2_to_int(v):
    return ZZ(v.polynomial().change_ring(ZZ)(2))


def half_trace(a, n):
    """The half-trace of a in GF(2^n), n odd: a solution z of z^2 + z = a when
    Tr(a) = 0 (the other is z + 1); callers check the trace first."""
    return sum(a^(2^(2 * i)) for i in range((n + 1) // 2))


# --- emit ----------------------------------------------------------------------
SEEDS = [
    # block 0 and block 1 hashes, display (big-endian) byte order
    bytes.fromhex("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"),
    bytes.fromhex("00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048"),
    hashlib.sha256(b"ephemeral-ecmh/kat/2").digest(),
    hashlib.sha256(b"ephemeral-ecmh/kat/3").digest(),
]
NMSG = 8


def write_struct(out, script, output, struct_doc=(), rejection_doc=(), extra=()):
    """The `CertKat` header, `output` being the file the script writes.
    `struct_doc` lines precede the struct, `rejection_doc` lines the rejections
    field, and `extra` lines (doc and fields) follow `sum`. Lines are written
    as given, with the `/// ` and indentation."""
    out.write("// @generated by sage/%s; do not edit. Regenerate from the repository root:\n" % script)
    out.write("//   nix develop .#math -c sage sage/%s > %s && nix fmt\n" % (script, output))
    out.write("#![allow(dead_code)]\n\n")
    for line in struct_doc:
        out.write(line + "\n")
    out.write("pub struct CertKat {\n    pub seed: [u8; 32],\n    pub index: u32,\n    pub r: u128,\n")
    for line in rejection_doc:
        out.write(line + "\n")
    out.write("    pub rejections: &'static [(u128, u128)],\n")
    out.write("    /// hash_to_curve(Salted::new(b\"kat\", seed), [i]) for i in 0..%d, encoded\n" % NMSG)
    out.write("    pub hashes: [u128; %d],\n" % NMSG)
    out.write("    /// encoded sum of `hashes`\n    pub sum: u128,\n")
    for line in extra:
        out.write(line + "\n")
    out.write("}\n")


def write_cert(out, seed, i, r, rej, hashes, total, width, extra=()):
    """One `CertKat` entry; `hashes`, `total` and `extra` values are encoded
    integers, written as 0x with `width` hex digits."""
    width = int(width)
    out.write("    CertKat {\n        seed: %s,\n" % list(seed))
    out.write("        index: %d,\n        r: 0x%x,\n        rejections: &[\n" % (i, r))
    for l, c in rej:
        out.write("            (0x%x, 0x%0*x),\n" % (l, width, c))
    out.write("        ],\n        hashes: [\n")
    for h in hashes:
        out.write("            0x%0*x,\n" % (width, h))
    out.write("        ],\n        sum: 0x%0*x,\n" % (width, total))
    for name, value in extra:
        out.write("        %s: 0x%0*x,\n" % (name, width, value))
    out.write("    },\n")
