# Point counts for the Rust prover's PARI-free tests (src/curvegen/prove.rs): the
# order of every candidate up to the accepted one, for the first KAT seed of
# each family, and the smallest prime factor of each composite the prover
# has to factor.
#
#   nix develop .#math -c sage sage/prove_orders.sage > tests/common/orders.rs
#   nix fmt
#
# The candidate framing is the same as sage/kat.sage (and src/curvegen/select.rs).
import hashlib, sys

MASK = 2^127 - 1


def salted(tag, salt, msg, ctr):
    t = hashlib.sha256(tag).digest()
    return hashlib.sha256(t + t + salt + bytes(32) + msg + int(ctr).to_bytes(4, "little")).digest()


def candidate(tag, seed, j):
    return int.from_bytes(salted(tag, seed, b"", j)[:16], "little") & MASK


R.<t> = GF(2)[]
K.<z> = GF(2^127, modulus=t^127 + t^63 + 1)
p = 2^127 - 1
F = GF(p)


def gf2_orders(seed):
    """(B, #E) per candidate; the odd part r = #E/2 is what gets factored."""
    for j in range(10^4):
        v = candidate(b"ephemeral-ecmh/curve/gf2", seed, j)
        n = EllipticCurve(K, [1, 1, 0, 0, K(ZZ(v).digits(2))]).order()
        yield v, n, n // 2
        if (n // 2).is_pseudoprime():
            return


def fp_orders(seed):
    """(d, #E) per non-square d; r = #E/4 is factored unless 8 | #E."""
    for j in range(10^4):
        d = F(candidate(b"ephemeral-ecmh/curve/fp127", seed, j))
        if d.is_square():
            continue
        n = EllipticCurve(F, [0, (1 + d) / 2, 0, (1 - d)^2 / 16, 0]).order()
        yield ZZ(d), n, (None if n % 8 == 0 else n // 4)
        if n % 8 != 0 and (n // 4).is_pseudoprime():
            return


def weier_orders(seed):
    """(b, #E) per nonsingular b; odd #E is factored."""
    for j in range(10^4):
        b = F(candidate(b"ephemeral-ecmh/curve/weier127", seed, j))
        if b in (0, 2, -2):
            continue
        n = EllipticCurve(F, [-3, b]).order()
        yield ZZ(b), n, (None if n % 2 == 0 else n)
        if n.is_pseudoprime() and n != p:
            return


SEED = bytes.fromhex("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f")

out = sys.stdout
out.write("// @generated by sage/prove_orders.sage; do not edit. Regenerate from the repository root:\n")
out.write("//   nix develop .#math -c sage sage/prove_orders.sage > tests/common/orders.rs && nix fmt\n")
out.write("#![allow(dead_code)]\n\n")
out.write("pub struct Orders {\n    pub seed: [u8; 32],\n")
out.write("    /// (curve parameter as an integer, #E) for each counted candidate\n")
out.write("    pub orders: &'static [(u128, u128)],\n")
out.write("    /// (composite m, smallest prime factor of m)\n")
out.write("    pub factors: &'static [(u128, u128)],\n}\n\n")

for name, orders in [("GF2_127", gf2_orders), ("FP127", fp_orders), ("WEIER127", weier_orders)]:
    rows = list(orders(SEED))
    out.write("pub const %s: Orders = Orders {\n    seed: %s,\n    orders: &[\n" % (name, list(SEED)))
    for v, n, _ in rows:
        out.write("        (0x%x, 0x%x),\n" % (v, n))
    out.write("    ],\n    factors: &[\n")
    for _, _, m in rows[:-1]:
        if m is not None:
            out.write("        (0x%x, 0x%x),\n" % (m, factor(m)[0][0]))
    out.write("    ],\n};\n\n")
    print("%s: %d candidates counted" % (name, len(rows)), file=sys.stderr)
