# Group orders of select.rs candidates, for the torsion sieve (src/curvegen/sieve.rs):
# the Rust sieve must find l | #E exactly when Sage's #E says so. Also
# prints, on stderr, how often each small l divides #E over a larger
# sample, and how many candidates a sieve up to L leaves for point counting.
#
#   nix develop .#math -c sage sage/sieve.sage > tests/common/sieve_vectors.rs
#   nix fmt
#
# The candidate derivation must match src/hash.rs and src/curvegen/select.rs.
import hashlib, sys

MASK = 2^127 - 1
NVEC = 200  # emitted per family
NSTAT = int(sys.argv[1]) if len(sys.argv) > 1 else 1000  # counted per family
SEED = hashlib.sha256(b"ephemeral-ecmh/sieve").digest()


def salted(tag, salt, msg, ctr):
    t = hashlib.sha256(tag).digest()
    return hashlib.sha256(t + t + salt + bytes(32) + msg + int(ctr).to_bytes(4, "little")).digest()


def candidate(tag, j):
    return int.from_bytes(salted(tag, SEED, b"", j)[:16], "little") & MASK


R.<t> = GF(2)[]
K.<z> = GF(2^127, modulus=t^127 + t^63 + 1)
p = 2^127 - 1
F = GF(p)


def gf2_curves():
    for j in range(2^32):
        v = candidate(b"ephemeral-ecmh/curve/gf2", j)
        if v != 0:
            yield j, EllipticCurve(K, [1, 1, 0, 0, K(ZZ(v).digits(2))])


def fp_curves():
    for j in range(2^32):
        d = F(candidate(b"ephemeral-ecmh/curve/fp127", j))
        if not d.is_square():
            yield j, EllipticCurve(F, [0, (1 + d) / 2, 0, (1 - d)^2 / 16, 0])


def weier_curves():
    for j in range(2^32):
        b = F(candidate(b"ephemeral-ecmh/curve/weier127", j))
        if b not in (0, 2, -2):
            yield j, EllipticCurve(F, [-3, b])


# name, curves, q, cofactor, the sieve's first (always-tried) l, and
# whether that l is a rejection "l | #E" (2) or "8 | #E" (8)
FAMILIES = [
    ("GF2_127", gf2_curves, 2^127, 2, None),
    ("FP127", fp_curves, p, 4, 8),
    ("WEIER127", weier_curves, p, 1, 2),
]
LS = [3, 5, 7, 11, 13, 17, 19, 23]


def theory(q, l):
    """Pr[l | #E] for a random curve over F_q, with Frobenius a random
    element of GL_2(F_l) of determinant q: it has eigenvalue 1 with
    probability l/(l^2 - 1) if q = 1 mod l (2/3 for l = 2), else 1/(l - 1)."""
    if q % l == 1:
        return l / (l^2 - 1)
    return 1 / (l - 1)


out = sys.stdout
out.write("// @generated by sage/sieve.sage; do not edit. Regenerate from the repository root:\n")
out.write("//   nix develop .#math -c sage sage/sieve.sage > tests/common/sieve_vectors.rs && nix fmt\n")
out.write("#![allow(dead_code)]\n\n")
out.write("/// The seed the candidates are derived from (`select::*_candidate`).\n")
out.write("pub const SEED: [u8; 32] = %s;\n\n" % list(SEED))

for name, curves, q, h, first in FAMILIES:
    orders = []
    for j, E in curves():
        orders.append((j, E.order()))
        if len(orders) == NSTAT:
            break
    out.write("/// (candidate index j, #E) for the first %d candidates with a curve.\n" % NVEC)
    out.write("pub const %s: &[(u32, u128)] = &[\n" % name)
    for j, n in orders[:NVEC]:
        out.write("    (%d, 0x%x),\n" % (j, n))
    out.write("];\n\n")

    # --- statistics over all NSTAT ------------------------------------------
    err = sys.stderr
    N = len(orders)
    ns = [n for _, n in orders]
    valid = sum(1 for n in ns if n % h == 0 and is_pseudoprime(n // h) and n // h != p)
    print("%s: %d curves, %d valid (r prime)" % (name, N, valid), file=err)
    if first == 8:
        k = sum(1 for n in ns if n % 8 == 0)
        print("  l = 8: %.3f of curves have 8 | #E" % (k / N), file=err)
    if first == 2:
        k = sum(1 for n in ns if n % 2 == 0)
        print("  l = 2: %.3f (theory 2/3)" % (k / N), file=err)
    for l in LS:
        k = sum(1 for n in ns if n % l == 0)
        print("  l = %2d: %.3f (theory %.3f)" % (l, k / N, float(theory(q, l))), file=err)
    # fraction left for point counting by a sieve up to L, and how many of
    # those are then accepted
    for L in [1, 3, 5, 7, 11, 13, 17, 19, 23]:
        def passes(n):
            if first == 8 and n % 8 == 0:
                return False
            if first == 2 and n % 2 == 0:
                return False
            return all(n % l != 0 for l in LS if l <= L)
        left = sum(1 for n in ns if passes(n))
        print("  sieve to %2d: %.3f left to count, %.3f of those valid" % (L, left / N, valid / max(left, 1)), file=err)
