// @generated by sage/prove_orders.sage; do not edit. Regenerate from the repository root:
//   nix develop .#math -c sage sage/prove_orders.sage > tests/common/orders.rs && nix fmt
#![allow(dead_code)]

pub struct Orders {
    pub seed: [u8; 32],
    /// (curve parameter as an integer, #E) for each counted candidate
    pub orders: &'static [(u128, u128)],
    /// (composite m, smallest prime factor of m)
    pub factors: &'static [(u128, u128)],
}

pub const GF2_127: Orders = Orders {
    seed: [
        0, 0, 0, 0, 0, 25, 214, 104, 156, 8, 90, 225, 101, 131, 30, 147, 79, 247, 99, 174, 70, 162,
        166, 193, 114, 179, 241, 182, 10, 140, 226, 111,
    ],
    orders: &[
        (
            0x231996a5b2214bd215b3462bfed56226,
            0x7fffffffffffffff744aa8ebe66211d2,
        ),
        (
            0x39e4e3fbe5da9a8755fce59567e8c022,
            0x7ffffffffffffffeeea52339a3a58172,
        ),
        (
            0x2343ac93306fed2cd80f18d0da39bb0d,
            0x8000000000000000e9e93566dcfbc2fe,
        ),
        (
            0x3348d186565bbd671b832cf14ecebf3b,
            0x80000000000000014a63175c849e35fe,
        ),
        (
            0x776cf3e26468c5c7615b7d8ff6ddc016,
            0x7fffffffffffffffbc08ee50b02d1672,
        ),
        (
            0x3e44021d1cb5e27283253f107f5824bd,
            0x7ffffffffffffffff290c805c69d802e,
        ),
        (
            0x278e05400ff506644f35cb572a1a37d3,
            0x80000000000000008ebda483dfdff756,
        ),
        (
            0x4287354c8f95975afc8233a17a84fe06,
            0x80000000000000013bedfff7d177163a,
        ),
        (
            0x173fbe884ddfc122c8a8678570c215d5,
            0x7fffffffffffffff54017c4652c619de,
        ),
        (
            0x4a0ec32e1b7c7731d8c6c76b5f8d65ac,
            0x800000000000000149b393f2b05f07da,
        ),
        (
            0x45ab5386035abbe319ac92cd476d16fa,
            0x7fffffffffffffffb85932eee674933a,
        ),
        (
            0x50116dd0d57ca7f895825f392b67f505,
            0x8000000000000000270b1d6a2dec8b1e,
        ),
        (
            0x6f27408663680c1ea9799d3691d0d05e,
            0x7fffffffffffffff8f8d1945465a1de2,
        ),
        (
            0x306ea00fadb271f9f1ecc15aa040a3c1,
            0x7fffffffffffffff0c3fd5f6bab45f06,
        ),
        (
            0x1b546cb4af6c44f84d2b2d3ad613bd88,
            0x800000000000000160109381b68db142,
        ),
        (
            0x728ae2ca604460be3bb6a8ee74f51813,
            0x8000000000000001432db6675df96d86,
        ),
        (
            0x2c526117bb928183022a561cc8c64142,
            0x80000000000000006dce1c50fd29ce02,
        ),
        (
            0x5accbd2f4129aed2a46e0f356b487d0e,
            0x8000000000000000808f0ad0f09a3f2a,
        ),
        (
            0x3ccee2f82f216f9249740e68b145719e,
            0x7fffffffffffffff9cb6a58251b05852,
        ),
        (
            0x2c283b3dc1b7409ad53d378284117412,
            0x8000000000000000c995465238819aea,
        ),
        (
            0x7de980712770a858ebf97352e66430db,
            0x8000000000000000bdbe2f06709e5316,
        ),
        (
            0x5cdc16bfb0bb3214e42813a247dcc0c9,
            0x7fffffffffffffffe6d892b8ed1de106,
        ),
        (
            0x2d6b560bd3b5f09eab6c4e822a6bc611,
            0x8000000000000000abcdee611a2e956e,
        ),
        (
            0x435d9332bd473396b06481c8cb9e0402,
            0x80000000000000014d714092f8bd7782,
        ),
        (
            0x1dc67430bbb60f0b3353fecc041a3873,
            0x8000000000000000682c24a1ed844ffe,
        ),
        (
            0x31449c7facad217fc8a499d51ff159af,
            0x7fffffffffffffff63a84381d8365b26,
        ),
        (
            0x336967a69a2867d44e23a85eb1c58885,
            0x7fffffffffffffff28185b5386838b06,
        ),
        (
            0x7eb3e70bc9083ae1594fa29d9ebff2a2,
            0x80000000000000002f2c850a1d4f453a,
        ),
        (
            0x7f5b688a749735cf99d5b730b9eca9f3,
            0x7fffffffffffffffc75fc4e0b6c7791e,
        ),
        (
            0x68f63e58ad67c92206f84530e5da2635,
            0x7fffffffffffffff74febcbc5d85a0f6,
        ),
        (
            0x3f7429ac6d20832a04b59c81fca467f1,
            0x80000000000000007c9fe2a96b6290a6,
        ),
    ],
    factors: &[
        (0x3fffffffffffffffba255475f33108e9, 0x3),
        (0x3fffffffffffffff7752919cd1d2c0b9, 0xb),
        (0x400000000000000074f49ab36e7de17f, 0x3),
        (0x4000000000000000a5318bae424f1aff, 0x3),
        (0x3fffffffffffffffde04772858168b39, 0x4f5b6984b6f7),
        (0x3ffffffffffffffff9486402e34ec017, 0xb),
        (0x4000000000000000475ed241efeffbab, 0x3),
        (0x40000000000000009df6fffbe8bb8b1d, 0x3),
        (0x3fffffffffffffffaa00be2329630cef, 0x3),
        (0x4000000000000000a4d9c9f9582f83ed, 0x3),
        (0x3fffffffffffffffdc2c9977733a499d, 0x3),
        (0x400000000000000013858eb516f6458f, 0x2b),
        (0x3fffffffffffffffc7c68ca2a32d0ef1, 0x5),
        (0x3fffffffffffffff861feafb5d5a2f83, 0x3),
        (0x4000000000000000b00849c0db46d8a1, 0x3),
        (0x4000000000000000a196db33aefcb6c3, 0x7),
        (0x400000000000000036e70e287e94e701, 0x3),
        (0x400000000000000040478568784d1f95, 0x3),
        (0x3fffffffffffffffce5b52c128d82c29, 0xb),
        (0x400000000000000064caa3291c40cd75, 0x3),
        (0x40000000000000005edf1783384f298b, 0x5),
        (0x3ffffffffffffffff36c495c768ef083, 0x5),
        (0x400000000000000055e6f7308d174ab7, 0x3),
        (0x4000000000000000a6b8a0497c5ebbc1, 0x3),
        (0x400000000000000034161250f6c227ff, 0x5),
        (0x3fffffffffffffffb1d421c0ec1b2d93, 0x315d4788f),
        (0x3fffffffffffffff940c2da9c341c583, 0x5),
        (0x4000000000000000179642850ea7a29d, 0x3),
        (0x3fffffffffffffffe3afe2705b63bc8f, 0xd),
        (0x3fffffffffffffffba7f5e5e2ec2d07b, 0x5),
    ],
};
