// @generated by sage/prove_orders.sage; do not edit. Regenerate from the repository root:
//   nix develop .#math -c sage sage/prove_orders.sage > tests/common/orders.rs && nix fmt
#![allow(dead_code)]

pub struct Orders {
    pub seed: [u8; 32],
    /// (curve parameter as an integer, #E) for each counted candidate
    pub orders: &'static [(u128, u128)],
    /// (composite m, smallest prime factor of m)
    pub factors: &'static [(u128, u128)],
}

pub const GF2_127: Orders = Orders {
    seed: [
        0, 0, 0, 0, 0, 25, 214, 104, 156, 8, 90, 225, 101, 131, 30, 147, 79, 247, 99, 174, 70, 162,
        166, 193, 114, 179, 241, 182, 10, 140, 226, 111,
    ],
    orders: &[
        (
            0x231996a5b2214bd215b3462bfed56226,
            0x7fffffffffffffff744aa8ebe66211d2,
        ),
        (
            0x39e4e3fbe5da9a8755fce59567e8c022,
            0x7ffffffffffffffeeea52339a3a58172,
        ),
        (
            0x2343ac93306fed2cd80f18d0da39bb0d,
            0x8000000000000000e9e93566dcfbc2fe,
        ),
        (
            0x3348d186565bbd671b832cf14ecebf3b,
            0x80000000000000014a63175c849e35fe,
        ),
        (
            0x776cf3e26468c5c7615b7d8ff6ddc016,
            0x7fffffffffffffffbc08ee50b02d1672,
        ),
        (
            0x3e44021d1cb5e27283253f107f5824bd,
            0x7ffffffffffffffff290c805c69d802e,
        ),
        (
            0x278e05400ff506644f35cb572a1a37d3,
            0x80000000000000008ebda483dfdff756,
        ),
        (
            0x4287354c8f95975afc8233a17a84fe06,
            0x80000000000000013bedfff7d177163a,
        ),
        (
            0x173fbe884ddfc122c8a8678570c215d5,
            0x7fffffffffffffff54017c4652c619de,
        ),
        (
            0x4a0ec32e1b7c7731d8c6c76b5f8d65ac,
            0x800000000000000149b393f2b05f07da,
        ),
        (
            0x45ab5386035abbe319ac92cd476d16fa,
            0x7fffffffffffffffb85932eee674933a,
        ),
        (
            0x50116dd0d57ca7f895825f392b67f505,
            0x8000000000000000270b1d6a2dec8b1e,
        ),
        (
            0x6f27408663680c1ea9799d3691d0d05e,
            0x7fffffffffffffff8f8d1945465a1de2,
        ),
        (
            0x306ea00fadb271f9f1ecc15aa040a3c1,
            0x7fffffffffffffff0c3fd5f6bab45f06,
        ),
        (
            0x1b546cb4af6c44f84d2b2d3ad613bd88,
            0x800000000000000160109381b68db142,
        ),
        (
            0x728ae2ca604460be3bb6a8ee74f51813,
            0x8000000000000001432db6675df96d86,
        ),
        (
            0x2c526117bb928183022a561cc8c64142,
            0x80000000000000006dce1c50fd29ce02,
        ),
        (
            0x5accbd2f4129aed2a46e0f356b487d0e,
            0x8000000000000000808f0ad0f09a3f2a,
        ),
        (
            0x3ccee2f82f216f9249740e68b145719e,
            0x7fffffffffffffff9cb6a58251b05852,
        ),
        (
            0x2c283b3dc1b7409ad53d378284117412,
            0x8000000000000000c995465238819aea,
        ),
        (
            0x7de980712770a858ebf97352e66430db,
            0x8000000000000000bdbe2f06709e5316,
        ),
        (
            0x5cdc16bfb0bb3214e42813a247dcc0c9,
            0x7fffffffffffffffe6d892b8ed1de106,
        ),
        (
            0x2d6b560bd3b5f09eab6c4e822a6bc611,
            0x8000000000000000abcdee611a2e956e,
        ),
        (
            0x435d9332bd473396b06481c8cb9e0402,
            0x80000000000000014d714092f8bd7782,
        ),
        (
            0x1dc67430bbb60f0b3353fecc041a3873,
            0x8000000000000000682c24a1ed844ffe,
        ),
        (
            0x31449c7facad217fc8a499d51ff159af,
            0x7fffffffffffffff63a84381d8365b26,
        ),
        (
            0x336967a69a2867d44e23a85eb1c58885,
            0x7fffffffffffffff28185b5386838b06,
        ),
        (
            0x7eb3e70bc9083ae1594fa29d9ebff2a2,
            0x80000000000000002f2c850a1d4f453a,
        ),
        (
            0x7f5b688a749735cf99d5b730b9eca9f3,
            0x7fffffffffffffffc75fc4e0b6c7791e,
        ),
        (
            0x68f63e58ad67c92206f84530e5da2635,
            0x7fffffffffffffff74febcbc5d85a0f6,
        ),
        (
            0x3f7429ac6d20832a04b59c81fca467f1,
            0x80000000000000007c9fe2a96b6290a6,
        ),
    ],
    factors: &[
        (0x3fffffffffffffffba255475f33108e9, 0x3),
        (0x3fffffffffffffff7752919cd1d2c0b9, 0xb),
        (0x400000000000000074f49ab36e7de17f, 0x3),
        (0x4000000000000000a5318bae424f1aff, 0x3),
        (0x3fffffffffffffffde04772858168b39, 0x4f5b6984b6f7),
        (0x3ffffffffffffffff9486402e34ec017, 0xb),
        (0x4000000000000000475ed241efeffbab, 0x3),
        (0x40000000000000009df6fffbe8bb8b1d, 0x3),
        (0x3fffffffffffffffaa00be2329630cef, 0x3),
        (0x4000000000000000a4d9c9f9582f83ed, 0x3),
        (0x3fffffffffffffffdc2c9977733a499d, 0x3),
        (0x400000000000000013858eb516f6458f, 0x2b),
        (0x3fffffffffffffffc7c68ca2a32d0ef1, 0x5),
        (0x3fffffffffffffff861feafb5d5a2f83, 0x3),
        (0x4000000000000000b00849c0db46d8a1, 0x3),
        (0x4000000000000000a196db33aefcb6c3, 0x7),
        (0x400000000000000036e70e287e94e701, 0x3),
        (0x400000000000000040478568784d1f95, 0x3),
        (0x3fffffffffffffffce5b52c128d82c29, 0xb),
        (0x400000000000000064caa3291c40cd75, 0x3),
        (0x40000000000000005edf1783384f298b, 0x5),
        (0x3ffffffffffffffff36c495c768ef083, 0x5),
        (0x400000000000000055e6f7308d174ab7, 0x3),
        (0x4000000000000000a6b8a0497c5ebbc1, 0x3),
        (0x400000000000000034161250f6c227ff, 0x5),
        (0x3fffffffffffffffb1d421c0ec1b2d93, 0x315d4788f),
        (0x3fffffffffffffff940c2da9c341c583, 0x5),
        (0x4000000000000000179642850ea7a29d, 0x3),
        (0x3fffffffffffffffe3afe2705b63bc8f, 0xd),
        (0x3fffffffffffffffba7f5e5e2ec2d07b, 0x5),
    ],
};

pub const FP127: Orders = Orders {
    seed: [
        0, 0, 0, 0, 0, 25, 214, 104, 156, 8, 90, 225, 101, 131, 30, 147, 79, 247, 99, 174, 70, 162,
        166, 193, 114, 179, 241, 182, 10, 140, 226, 111,
    ],
    orders: &[
        (
            0x55652782103fa34fa885245ed36d1c4a,
            0x7fffffffffffffff8d9d6e24c134e9e4,
        ),
        (
            0x1b820417331b5451765a6723c57d73b7,
            0x800000000000000012ae705677e13458,
        ),
        (
            0x68707c4697fc5086f7e0fc0515432b7e,
            0x7fffffffffffffffcc61ff9e0ef1d500,
        ),
        (
            0x16288c7484d115e6c27d464e52f974ec,
            0x800000000000000034338371579ffa2c,
        ),
        (
            0x5722f0b4f7d537485845f38e86820cf6,
            0x7fffffffffffffffc809c9bdc6bcc4b0,
        ),
        (
            0x465b526873ae1b635adad3926d6d6db3,
            0x80000000000000006834984692984bf0,
        ),
        (
            0x675af0579768bfa5ba14441cfdc5657,
            0x7fffffffffffffff561d805a4465bc60,
        ),
        (
            0x11bf0903959bc44162f0c67e3b1c258a,
            0x80000000000000010167a1d3f6a3697c,
        ),
        (
            0x5888735aadb05b5a22790dc709d35685,
            0x7fffffffffffffff45b9202cfe8a5c7c,
        ),
        (
            0x40825567539028e2813552ab82e8521c,
            0x80000000000000001ac51ed34a950bd0,
        ),
        (
            0x7c6a413b4dc1c6bdbff6a5f023c8a777,
            0x7ffffffffffffffea61b7adc1639e620,
        ),
        (
            0x79a656e2a4355193a2d6fb237d4a22f9,
            0x7fffffffffffffff914717243166f238,
        ),
        (
            0x24d1d2c8000fc498eb3ee82f6bd66ed0,
            0x800000000000000070876663f1f2b2f8,
        ),
        (
            0x3897deea2810ff52b8792a008fcc52f3,
            0x7fffffffffffffff36e651426e568c34,
        ),
        (
            0x3d7826cacda896d29b1f392774fa5ec9,
            0x7fffffffffffffffa5b8d90304655540,
        ),
        (
            0x748449803a7cee4c6d19420d83f8e817,
            0x800000000000000031dcb0b945e95d60,
        ),
        (
            0x73cec04d6f9dc15ac55d5269e509a02f,
            0x80000000000000001a4521c55af6ef68,
        ),
        (
            0x11bbc5234d2c813dcfafa1cbda710c77,
            0x8000000000000000a54010a6d678c2e8,
        ),
        (
            0x5e2b94306eafb9016b158a06d3ba7f38,
            0x7fffffffffffffff651d0d5e685114ac,
        ),
        (
            0x3a2c54066ea6043aab87a89b398be0d1,
            0x7fffffffffffffff312dcc9ce9b25b48,
        ),
        (
            0x2ed2197f66cf045209a7a02ef4c8ff50,
            0x7ffffffffffffffffb4c34089def1b04,
        ),
        (
            0x8fc6dbff2585447e3497435dcfb2159,
            0x7fffffffffffffff55a7b10dba6e15c8,
        ),
        (
            0x9ebc711b1a02384640b85f64c604957,
            0x7ffffffffffffffeed5c9af8ac33a510,
        ),
        (
            0x7826db3bb88ae05adb722366184e5a0b,
            0x7fffffffffffffffc5ccecf0eedf7028,
        ),
        (
            0x24c9985dd6cfbbc7a8725b0533e1382b,
            0x80000000000000000a9875a03cb75ce4,
        ),
        (
            0x7f86dd9630bc961baf0d5f9997b25ef6,
            0x8000000000000000fb163db4158ce1ac,
        ),
        (
            0x546b2fc1c322603175660e2272f49ba8,
            0x7fffffffffffffff92356bcb9b177710,
        ),
        (
            0x6aa704953af6b4e165599c3b0060189e,
            0x80000000000000005e6b403dedef7288,
        ),
        (
            0x3fea09f98fd24dc61dfbab5affa26ff0,
            0x800000000000000006e9d43d73916070,
        ),
        (
            0x2214a427d90bc8e41814eda55d19fa42,
            0x7ffffffffffffffee2c2f86a9e0ff470,
        ),
        (
            0x1b614e17b13bd0df68713703a7b1b7c,
            0x7fffffffffffffffa605d55383cee3bc,
        ),
        (
            0x5a81b78d3179fd4156b84e32b7ec9670,
            0x80000000000000008c66d72ecb019efc,
        ),
        (
            0x5cf9bd826f282d6362d16d2cd4548999,
            0x80000000000000003cd1c822d71c27f4,
        ),
        (
            0x62543694f853fcbb5e8b1e46de7855ae,
            0x7fffffffffffffff73b287fd4eb41300,
        ),
        (
            0x14334ffa6d08e279a3ba12120815b117,
            0x8000000000000000155f7e603c394254,
        ),
        (
            0x34d2c9946bbf94baf06a1d9e1fa3e992,
            0x80000000000000005406cd03176a34e4,
        ),
        (
            0x1031e514c4fcd09ff8a106b39c471fcb,
            0x800000000000000088f81ccdbcf955d4,
        ),
        (
            0x18a62cd6dddcb539ab64ca1988126c36,
            0x80000000000000009b2321efff665198,
        ),
        (
            0x1b6cfa5605dea9bc92ff733a3f53a079,
            0x7fffffffffffffffc938c0882b6e5284,
        ),
        (
            0xfa2950e0ba2d34a599d814e80ce197a,
            0x7fffffffffffffff21ee20a33839e7e8,
        ),
        (
            0x400922e18a2da5c5352d84aa5d0380dd,
            0x8000000000000000b4f8fdb3f98bbff0,
        ),
        (
            0x60d2675d4cafaae4e053d77df1389c8d,
            0x800000000000000066e08a90ad79bca0,
        ),
        (
            0x33a0e38ca787de4737d586c5787272d0,
            0x80000000000000005a64eddf50b6cdd4,
        ),
        (
            0x4b515e1a6f6b340a2f75dec1640bd8f9,
            0x8000000000000000afbf5d5b9f6f47ac,
        ),
        (
            0x7884562f5b4b7165f6d8afa9d8f72777,
            0x7fffffffffffffff1e6831f227967e0c,
        ),
        (
            0x376f24fe80c7fd0d6461c988548c9b6d,
            0x8000000000000000d1a155d5b57d9720,
        ),
        (
            0x42fb62b7b100839c84951a76fc7ac550,
            0x800000000000000065cdb3c8f8c00254,
        ),
        (
            0x61134788451da16252cee313df2b4553,
            0x7ffffffffffffffee6d7f5a25475098c,
        ),
        (
            0x286866de8c278ff81336d40d58ddaa37,
            0x7fffffffffffffffbe81837fdd4c3510,
        ),
        (
            0x4128d3acf2959ec01afb9f9acb22533c,
            0x800000000000000003441789385014f0,
        ),
        (
            0x3a6fb6f2c5a7c1226ce30e819a731dca,
            0x7fffffffffffffffa89ad3839fadac74,
        ),
        (
            0x1d6ce4443636b8d66a4312dc5c4cea67,
            0x80000000000000009b566505f786a6d0,
        ),
        (
            0x73df669d47b97af69b1648fa87adbefe,
            0x800000000000000092e77f4a9fe27fc8,
        ),
        (
            0x409e8172d059dc3fb14edb6f389bcae8,
            0x800000000000000020557b67f12bc8ac,
        ),
        (
            0x2e1fede5327f8ce6e7152dbf0ce01f76,
            0x80000000000000012f371f4f825ab068,
        ),
        (
            0x8c16d2568cbc0fa9e1baf546dc540a,
            0x8000000000000000ccb0e8d83b780674,
        ),
        (
            0x18e7ad12a74de3c218133ea15c75f8c2,
            0x8000000000000000da0edc3487767dec,
        ),
    ],
    factors: &[
        (0x1fffffffffffffffe3675b89304d3a79, 0xb),
        (0x20000000000000000d0ce0dc55e7fe8b, 0x5),
        (0x20000000000000004059e874fda8da5f, 0x3497),
        (0x1fffffffffffffffd16e480b3fa2971f, 0x3),
        (0x1fffffffffffffffcdb994509b95a30d, 0x13),
        (0x1fffffffffffffffd94743579a14452b, 0x3),
        (0x1ffffffffffffffffed30d02277bc6c1, 0xd),
        (0x200000000000000002a61d680f2dd739, 0x5),
        (0x20000000000000003ec58f6d0563386b, 0x3),
        (0x1fffffffffffffffe9817554e0f3b8ef, 0x7),
        (0x20000000000000002319b5cbb2c067bf, 0x3),
        (0x20000000000000000f347208b5c709fd, 0x97),
        (0x20000000000000000557df980f0e5095, 0x17),
        (0x20000000000000001501b340c5da8d39, 0x5),
        (0x2000000000000000223e07336f3e5575, 0x3),
        (0x1ffffffffffffffff24e30220adb94a1, 0x265),
        (0x200000000000000016993b77d42db375, 0x7),
        (0x20000000000000002befd756e7dbd1eb, 0x3),
        (0x1fffffffffffffffc79a0c7c89e59f83, 0x3),
        (0x200000000000000019736cf23e300095, 0x167),
        (0x1fffffffffffffffb9b5fd68951d4263, 0x7),
        (0x1fffffffffffffffea26b4e0e7eb6b1d, 0x11),
        (0x200000000000000008155ed9fc4af22b, 0x89),
        (0x2000000000000000332c3a360ede019d, 0x3),
    ],
};

pub const WEIER127: Orders = Orders {
    seed: [
        0, 0, 0, 0, 0, 25, 214, 104, 156, 8, 90, 225, 101, 131, 30, 147, 79, 247, 99, 174, 70, 162,
        166, 193, 114, 179, 241, 182, 10, 140, 226, 111,
    ],
    orders: &[
        (
            0x5c58eab7662720c7d67931aa9af3049a,
            0x7fffffffffffffff9f9699f307affa5a,
        ),
        (
            0x5b60290fb5a88c33e5df1c8d3d26627e,
            0x80000000000000011b6683481c725e4b,
        ),
        (
            0x65dda1c1351e3efaf3cb60be5b585d92,
            0x7fffffffffffffff866f426622dd2db2,
        ),
        (
            0x55934af4abaee2743be454e3b23e300c,
            0x7fffffffffffffff97aee69874cff6d2,
        ),
        (
            0x5adf5d6cf526e97f73d6a5aa680826f,
            0x800000000000000015bd741923214590,
        ),
        (
            0x6164ae2546979a5edbad5ce2afbab35a,
            0x8000000000000000b852bd81f5515bba,
        ),
        (
            0x193d7f6f0725058eb6e6709be41bf971,
            0x7fffffffffffffff5afd6e5e3ea47abc,
        ),
        (
            0x15f775a98cefc08f73b137edef31b637,
            0x7fffffffffffffff4374b1ebe0aedcbf,
        ),
        (
            0x261fb022f35cd9472872987e93402eeb,
            0x7fffffffffffffff5cb29f2639317cb0,
        ),
        (
            0x46b1c61e782d973b9f1dec2262b1825b,
            0x80000000000000004d55da4f29d09a63,
        ),
        (
            0x554f80efbedf4be66052f69b6cbdcb7b,
            0x800000000000000065b05df872463f94,
        ),
        (
            0x61c84faea4a8236d2d1f36d5cc9e123c,
            0x7fffffffffffffff4e7fa8748942cd42,
        ),
        (
            0x721f09353c53cf82477cef4b9e024df6,
            0x7fffffffffffffff9a20a4bdce1d4134,
        ),
        (
            0x5014785af70687c32fa414caffd1e5b0,
            0x8000000000000000c6d955e406dd490e,
        ),
        (
            0x602807d72b9d64b7f619f15838d17b81,
            0x7fffffffffffffff1d9206a184c94501,
        ),
        (
            0x4b3dd4fadaabb6a78887b2b300b3b0ce,
            0x7fffffffffffffffd76de6399749c2fe,
        ),
        (
            0x27aeaabe0d2e183cc390d919e25ffdfa,
            0x7fffffffffffffff00e0b14f04968c48,
        ),
        (
            0x94189d218adce4a7c0df085400ff9f4,
            0x80000000000000008b84095026086c79,
        ),
        (
            0xfec6e252c278c535ba03cd7f18d9962,
            0x8000000000000000bb5bf94057323ad5,
        ),
        (
            0x2779264db4fef983d061ca5808060f78,
            0x7fffffffffffffff60e916fba44c2d80,
        ),
        (
            0x39bc5b98b8fffd3e1fbcd09e3be03de1,
            0x8000000000000000fc49d48a1ef4f793,
        ),
        (
            0x700a3cd2666e3da9e39d2653db21393b,
            0x7fffffffffffffff06d34ba501b8ec6e,
        ),
        (
            0x626cff4dbd502ad43589246e549f8431,
            0x8000000000000000ba01467e099d7afc,
        ),
        (
            0x50b1e645452b63573d305342b54bc188,
            0x7ffffffffffffffff7e421edb83f8216,
        ),
        (
            0x500ebd6d54aa06b70c32eb65f8189928,
            0x7ffffffffffffffff6fe6da012e0effd,
        ),
        (
            0x5ccfbd02f5fce15b9adf0875dcb1710e,
            0x80000000000000007ecd862d92b2e6db,
        ),
        (
            0x5b6c6bcb8fd153a144b4f786f18e42d7,
            0x800000000000000084ff8ad68d4cebc0,
        ),
        (
            0x216ccdc2b10807d194c973aab8a1ca8d,
            0x80000000000000003656c87bc2f28128,
        ),
        (
            0x62fe83de25a67fa0d0572c48e5d6c1ce,
            0x7fffffffffffffffe02f83a03ac31e76,
        ),
        (
            0x3c8895f3aabdecf020fd195c58e1e1f7,
            0x7fffffffffffffff98f17f0f0f912849,
        ),
        (
            0x29230b12e22272ca9cb416b9fc03b7,
            0x7ffffffffffffffef3bb501db562a722,
        ),
        (
            0x5439435d3a526e942c84facd13eb9437,
            0x7fffffffffffffff8467122fa7dd4106,
        ),
        (
            0x22b459b25f6b401159faba9884ab8e8f,
            0x8000000000000000c888def9ab6a209c,
        ),
        (
            0x67b03865c90682352c6fb164f73adc70,
            0x7fffffffffffffff5ed4249e658d1e38,
        ),
        (
            0x163e49180d851655eb0e836e2288f651,
            0x8000000000000000360961bcc1e01d9f,
        ),
        (
            0x41095793e4e22d845672618823a8b2ae,
            0x800000000000000105ccabfe43cf8661,
        ),
        (
            0x7ec52c4bef9f9f9fe72063f34c9e9710,
            0x7ffffffffffffffeaf3e10835fd74b2c,
        ),
        (
            0x2804971e047addec8f1ec0049bbdf2d3,
            0x8000000000000000efa86da59edbb661,
        ),
        (
            0x6da6ede7879debb74b01a36eb9066616,
            0x8000000000000000cb008c69c8175bda,
        ),
        (
            0x2aa096b3bbb763ccebd76f1bb22d6028,
            0x8000000000000000a89f8b6098c029e2,
        ),
        (
            0x5bd8178bf5e0a53ad38fc72fb9545e6a,
            0x80000000000000001d5f8d60d122040b,
        ),
        (
            0x4e7aeb424638da492a4b3fe9d23819e2,
            0x7fffffffffffffff50d2aa47984eb443,
        ),
        (
            0xea8ae8642989e46aaf3e56cc3aaf349,
            0x7fffffffffffffff90693535c969b8d2,
        ),
        (
            0x4be30eaa9ca3abe7d67e12f8cce5f086,
            0x8000000000000000438065465eff60d0,
        ),
        (
            0x13b1389c24260f2198c63e67516fcd9d,
            0x7ffffffffffffffee9f6da38a9c4a8c8,
        ),
        (
            0x5729cae1086aed26ff2274f7ab1f2c5,
            0x8000000000000000ec0e1765641ed01a,
        ),
        (
            0x23b5ccafc67874b8d9d6df57e033e40b,
            0x80000000000000006d6de2bbf99e8b15,
        ),
        (
            0x31da7fd6e0d7d3241319840dc909d110,
            0x80000000000000008c53413656bd69fa,
        ),
        (
            0x74eae90e013819d3dbd80a132355918b,
            0x7ffffffffffffffff3888c88aceab7ea,
        ),
        (
            0x5da9313e5f9f5549849b5fb20c5287b8,
            0x800000000000000053c8a1b8b1276124,
        ),
        (
            0x393a6457c455e477f7a3cf8904f5b62d,
            0x8000000000000001107d4bcb87ebd38e,
        ),
        (
            0x2f56b2f66f673f3da107c09d6f2bf728,
            0x8000000000000000b941d2f24fcdcffa,
        ),
        (
            0xbd8cbebebae7114851c7a432df7b3f9,
            0x7ffffffffffffffeb32ebc8619095630,
        ),
        (
            0x2fd37369a12a34449d5f4b61e6e74834,
            0x80000000000000008a8a4f6e166b4bc0,
        ),
        (
            0x5238446a2036408b17916694c0796c75,
            0x8000000000000000b31f4aec3d2befb8,
        ),
        (
            0x3f01675aa0baef51fc16982c6baa2fe,
            0x80000000000000008dda5ed79a93c0b5,
        ),
        (
            0x6df3e4ffc1212ba773e7bce698025d8f,
            0x7fffffffffffffff5a55f684ade0ca97,
        ),
        (
            0x425955d0da1ad50a32f24ceaeec57115,
            0x8000000000000000e08408d8b8e40780,
        ),
        (
            0x52edea7c39c25fceaf6d6e9464e70af0,
            0x80000000000000002cfadbd095d67f86,
        ),
        (
            0x5cc3b2056a4ae6a04e9bbfe705a9af64,
            0x800000000000000028bdaaa207cb3742,
        ),
        (
            0x5af33ce651c96b51c9feb3b0e9d961c5,
            0x80000000000000002ea3991bb6fc257b,
        ),
        (
            0x4b5b105f54b857282352bfc94224e94e,
            0x7ffffffffffffffef57be6cd338ad3ad,
        ),
        (
            0x6385152946c2f933e2d177ee214428d,
            0x8000000000000000d7d3152dca9fda67,
        ),
        (
            0x2485095ea907ce7573e9f1b56effeedc,
            0x7fffffffffffffff751e1add15d664ae,
        ),
        (
            0x11c29d47308c357722a96a64d752009f,
            0x800000000000000070e9bb3564759f9b,
        ),
        (
            0x1924f587c8f8408a51036327a4cd4ff9,
            0x7fffffffffffffffd6d511ce25662eb9,
        ),
        (
            0x7e03ccf838a56670da5f732dcc39b14d,
            0x7fffffffffffffffc7d1680b6671f8a8,
        ),
        (
            0x6e8f36ec289ba3c385b5ce729c354fd3,
            0x7fffffffffffffff1a85843cdad77a3e,
        ),
        (
            0x236a3f6f6bf198f4c46105d10ac81d71,
            0x7ffffffffffffffffcdaff73ec7bac47,
        ),
        (
            0x67a6eb5502873405906e910a26cfcb48,
            0x7fffffffffffffffd3242f722559dcb8,
        ),
        (
            0x46e5afa18954f2ea323aefd14f06fbb1,
            0x8000000000000000a1c385da89060564,
        ),
        (
            0x75c430666670597a02de1887af0cac39,
            0x8000000000000000d995e29dfdfdf20e,
        ),
        (
            0x4e5916a7216d1dee796cec21b23bc857,
            0x7fffffffffffffffbc4ee81358738094,
        ),
        (
            0x7d402035531f28bed98fe5e6ca7ddc99,
            0x80000000000000001f996645b4f02640,
        ),
        (
            0x1e62e5c95d4a133bd83ee3115d2d799d,
            0x8000000000000000e6f10244d3469319,
        ),
        (
            0x75d919db719801a62058f121e98c2326,
            0x8000000000000000e97e5f14b4745307,
        ),
        (
            0x6140c82f97cc304cfeef7426e536fb61,
            0x800000000000000071f4f612c944a58f,
        ),
        (
            0x25ca1dcee97b7b472d7d129522d94430,
            0x7fffffffffffffffdc701ed58e77497a,
        ),
        (
            0x5334c53363bfc28f5c1340ff0ca98b0c,
            0x80000000000000010d1ee03ad35c3fb6,
        ),
        (
            0x6702db77a96b47405215e33bca60a61a,
            0x80000000000000004c91cfa730cb86c8,
        ),
        (
            0x3a183a0e3111869ffdd7904ca8041caa,
            0x8000000000000000f78abf026b61276a,
        ),
        (
            0x4b78053bef638f51acd6ec3834af3c97,
            0x80000000000000002afeb9d7ff19427c,
        ),
        (
            0x5c400939a15e7c8a658783a1f1341bb4,
            0x8000000000000000317bf5f59ad270c7,
        ),
        (
            0x48881649661222ceef0cb574658a33fa,
            0x7ffffffffffffffe9e0d22cae716891e,
        ),
        (
            0x5bca4ec75232251a9f02fec1bb3428b5,
            0x7ffffffffffffffee2fd2588e9ed382b,
        ),
        (
            0x338a50412eee79c6c31e9852e16c6a52,
            0x80000000000000003b5a43af98a21c8e,
        ),
        (
            0x6a6e4a1ef62ced1ef05aaa2d540bb336,
            0x800000000000000010c973be8082e99c,
        ),
        (
            0x2f601094a99c5009f435419378155690,
            0x8000000000000000e8b1ae458f7316c6,
        ),
        (
            0x590b582512d53070833fe7b348002196,
            0x7fffffffffffffffe914f337c4719cbc,
        ),
        (
            0x39bce5b2a3af6e4c28b42963b6e6a2a,
            0x80000000000000010bfd898b57775749,
        ),
        (
            0xb91d0b553da8f55e36913c34c0cbcfc,
            0x7fffffffffffffff14fd1e515a4e60ea,
        ),
        (
            0x5a911fcd08d886e8738993a67b673952,
            0x80000000000000009ae07de01cf3328c,
        ),
        (
            0x6d8356e34b45a463eb8a1da3a9f64d33,
            0x8000000000000000758bd3f5abb82a68,
        ),
        (
            0x894db4a9a8dbf0a6bb0cb6896fcff3b,
            0x7fffffffffffffff2f260473f05027a8,
        ),
        (
            0x305924dd408f62cbfff8784653a0710,
            0x8000000000000000351f83ac0b7252ec,
        ),
        (
            0x77ac776d66fae6067a304160cb58fa57,
            0x80000000000000011fa83a8e10b6dbb4,
        ),
        (
            0x7377865c22b6c30c718e36572752c8c9,
            0x80000000000000001d57e68d92bae12e,
        ),
        (
            0x2122a55843364bd724ae0c0d9a0bff5a,
            0x800000000000000099fc3da3a3a7f5c2,
        ),
        (
            0x30858b8e7925ee4f43395310399f0855,
            0x8000000000000000032acb64d2c2961e,
        ),
        (
            0x40cc94c3f60609cfdb11206df6816e9f,
            0x8000000000000000d2c40eb0f3a26055,
        ),
        (
            0x6ca2298e5c97ef50ce4e103acd31bfed,
            0x80000000000000013ca198fceddedaeb,
        ),
        (
            0x465297502e69ce72d69ab5be56f605d9,
            0x80000000000000009b586f280010ee68,
        ),
        (
            0x255d0913c25d923a32b6df5b721f4c51,
            0x7fffffffffffffffc2f34384b567dce2,
        ),
        (
            0xac028ee1436b4e52822978ae6f0e019,
            0x8000000000000000130948d3e73d7aa8,
        ),
        (
            0x3a695a497df5b028876ff3f833a325ba,
            0x7fffffffffffffffd6addd148b09e6a4,
        ),
        (
            0x26d32cf51d227ca336e0b41015850bfd,
            0x7ffffffffffffffee18b0fc39b68ca04,
        ),
        (
            0x148db22bb8478aacb08f044078c613f7,
            0x7fffffffffffffff14cabe2f3c2b154c,
        ),
        (
            0x733c075f94b6f98c4b00a9bcea3f8038,
            0x800000000000000134e97291b7fa2d54,
        ),
        (
            0x663e4270a06e4c97629ea1956154bcb5,
            0x80000000000000000febc8145e374004,
        ),
        (
            0x29d8ed7becaed0b29983ccacb5d901c8,
            0x7fffffffffffffff5987e0be17d16848,
        ),
        (
            0x35659c3c2e9edfc8eff847eb1a9443b3,
            0x7fffffffffffffff48162dfcf85d41ec,
        ),
        (
            0x28c06134d28271c74b6b246f45300411,
            0x7fffffffffffffff3f29acd38e238593,
        ),
        (
            0x9dfc23ac4173c809563892b3304a4e3,
            0x80000000000000006f62dfb63e7ec575,
        ),
        (
            0x259ad4b4984bd4f510b03b357688e48,
            0x7fffffffffffffff80a402f2533c87c8,
        ),
        (
            0x35d75d7262b4ab9452e58f4f572c4eb9,
            0x8000000000000001412be6914b291e5e,
        ),
        (
            0x3499416b0df887918cfeb4ec4872ea26,
            0x80000000000000001b04f3679e9a3d1b,
        ),
        (
            0x6faa4b7403b487d58313cff162d68667,
            0x80000000000000002c2cc96b9b7bc377,
        ),
        (
            0x54459b38347b956f8af34ada024461ff,
            0x7fffffffffffffffbbb35a87121f4dc8,
        ),
        (
            0x352aadbd743ec4618d32ce2eeac955ee,
            0x7fffffffffffffffbda1197b23463c09,
        ),
        (
            0x5da57adee2ab26c75fd1a88146865e10,
            0x7fffffffffffffff3a6570c5a7442bf0,
        ),
        (
            0x537a8690b4da0b49633f08ea3abd29cf,
            0x7ffffffffffffffebdc0a3832497129b,
        ),
        (
            0x48ccaef8fe902c89d0f238ff93756b50,
            0x7fffffffffffffffe85e7c7f6af50940,
        ),
        (
            0x22c7f320081645e20ddf2f30ebbff7d0,
            0x7fffffffffffffff5cdb92e0ec43e9d2,
        ),
        (
            0x201a7fb6e10f9c25bd8e508368133986,
            0x7fffffffffffffffd7b22385381d8c4c,
        ),
        (
            0xd162d8aa6993677b9d439884dd972e9,
            0x8000000000000000fce11ac353e4e750,
        ),
        (
            0x7fa0081246bc73f7e3c59c4fbf247061,
            0x7fffffffffffffffb304557ca1e7401d,
        ),
    ],
    factors: &[
        (0x80000000000000011b6683481c725e4b, 0xd),
        (0x7fffffffffffffff4374b1ebe0aedcbf, 0x493),
        (0x80000000000000004d55da4f29d09a63, 0x3),
        (0x7fffffffffffffff1d9206a184c94501, 0x7),
        (0x80000000000000008b84095026086c79, 0x4f),
        (0x8000000000000000bb5bf94057323ad5, 0xb),
        (0x8000000000000000fc49d48a1ef4f793, 0x1b1),
        (0x7ffffffffffffffff6fe6da012e0effd, 0x5),
        (0x80000000000000007ecd862d92b2e6db, 0x7),
        (0x7fffffffffffffff98f17f0f0f912849, 0x5),
        (0x8000000000000000360961bcc1e01d9f, 0x1f),
        (0x800000000000000105ccabfe43cf8661, 0x2f),
        (0x8000000000000000efa86da59edbb661, 0x5),
        (0x80000000000000001d5f8d60d122040b, 0x3),
        (0x7fffffffffffffff50d2aa47984eb443, 0x5),
        (0x80000000000000006d6de2bbf99e8b15, 0x3),
        (0x80000000000000008dda5ed79a93c0b5, 0x3),
        (0x7fffffffffffffff5a55f684ade0ca97, 0x5),
        (0x80000000000000002ea3991bb6fc257b, 0x83),
        (0x7ffffffffffffffef57be6cd338ad3ad, 0x17),
        (0x8000000000000000d7d3152dca9fda67, 0x3),
        (0x800000000000000070e9bb3564759f9b, 0x7),
        (0x7fffffffffffffffd6d511ce25662eb9, 0x2bd),
        (0x7ffffffffffffffffcdaff73ec7bac47, 0x3),
        (0x8000000000000000e6f10244d3469319, 0x3),
        (0x8000000000000000e97e5f14b4745307, 0xdd7bb0cf),
        (0x800000000000000071f4f612c944a58f, 0x3),
        (0x8000000000000000317bf5f59ad270c7, 0x5),
        (0x7ffffffffffffffee2fd2588e9ed382b, 0x3),
        (0x80000000000000010bfd898b57775749, 0x3),
        (0x8000000000000000d2c40eb0f3a26055, 0x5),
        (0x80000000000000013ca198fceddedaeb, 0xd),
        (0x7fffffffffffffff3f29acd38e238593, 0x3),
        (0x80000000000000006f62dfb63e7ec575, 0x1f),
        (0x80000000000000001b04f3679e9a3d1b, 0x5),
        (0x80000000000000002c2cc96b9b7bc377, 0x3),
        (0x7fffffffffffffffbda1197b23463c09, 0x7),
        (0x7ffffffffffffffebdc0a3832497129b, 0x3),
    ],
};
